#!/usr/bin/env bash

set -eu

if [[ " $* " != *" -u "* && " $* " != *" --unchecked "* ]]; then
    echo -e "Linter› *** tsc ***\n" >&2
    bunx tsc --noEmit --project tsconfig.build.json || error0="$?"

    echo -e "\nLinter› *** eslint ***" >&2
    bunx eslint || error1="$?"

    if [[ "${error0:-}" || "${error1:-}" ]]; then
        echo -e "\nLinter› \033[31m*** Errors found! ***\033[0m" >&2
        exit 1
    fi
fi

rm -rf ./dist

bun build ./src/index.ts \
    --target browser --production --sourcemap --outdir ./dist \
    --drop console.debug --drop debugger
